### ISSUE TITLE
Arquivo .bot e implantação do Bot

### ISSUE THREAD

**Issue by ThiagoBoccalon** [MicrosoftDocs/bot-docs.pt-br#2]
Após criar o Web Bot no Azure e fazer download não consegui encontrar o arquivo .bot da minha aplicação e também não consegui localizar botFileSecret nas Configurações do Aplicativo.

Estou tentando implantar um bot que fiz localmente e que utiliza os serviços Luis, QnAMaker e Dispatch, porém, estou esbarrando nesse ponto.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 9d5bd35d-3178-42cd-2893-3b6a4b7a94ce
* Version Independent ID: 1545fd44-d471-d947-f94d-4b5e8d6e853f
* Content: [Tutorial sobre como criar e implantar um bot básico - Bot Service](https://docs.microsoft.com/pt-br/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-tutorial-basic-deploy.md](https://github.com/MicrosoftDocs/bot-docs.pt-br/blob/live/articles/v4sdk/bot-builder-tutorial-basic-deploy.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by CeciAc** [comment]
Olá, @ThiagoBoccalon

Sua contribuição é muito bem-vinda. Nossa equipe analisou seus comentários e parece que esse problema foi já registrado. 

Verifique o problema https://github.com/MicrosoftDocs/bot-docs.pt-br/issues/1

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
